#centi meter
room_501:
  x: 873.5
  y: 1796.5

room_502:
  x: 873.5
  y: 1984.5

room_503:
  x: 873.5
  y: 2625

room_504:
  x: 873.5
  y: 3712.5

room_505:
  x: 873.5
  y: 4355.5

room_506:
  x: 681.5
  y: 4652

room_507:
  x: 681.5
  y: 2697.13

room_508:
  x: 687.5
  y: 1797.5

room_511:
  x: 538.6
  y: -646

  
############ 
# 5층 엘레베이터 앞 방화셔터 턱을 중심점으로 ⇒ 512호 

# x : +418cm, y : -718, x : 89, y : -380, x : -105, y : - 321, x : -10 
# v=rw
# rw*t = s (linear)

# curve
# left 255-40 1-cos // cycle T? -> experimental result
# right 255
# 이동 시나리오
# 1. 직진 418cm
# 2, 오른쪽으로 90도 회전
# 3. 직진 718cm
# 4. 왼쪽으로 90도 회전
# 5. 직진 89cm
# 6. 오른쪽으로 회전
# 7. 직진 380cm
# 8. 오른쪽으로 회전
# 9. 직진 105cm
# 10. 왼쪽으로 회전
# 11. 직진 321cm
# 12. 오른쪽으로 회전
# 13. 직진 10cm

# yaml파일에서 전체 x,y거리를 받아온다
# 그리고 상세한 경로로 나누고
# 그에 맞는 왼쪽, 오른쪽 rpm(int형, 0~255)를 구해서 
# 로스 토픽으로 보낸다.

############
room_512: 
  x: 392 #538.6
  y: -1246

room_513:
  x: 538.6
  y: -1419

room_514:
  x: 524.6
  y: -2441.5

room_515:
  x: 524.6
  y: -2617

room_524:
  x: 1349.5
  y: -2617

room_544:
  x: 1577
  y: 433.25